version: '3.3'

services:
  php:
    tty: true
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/var/www
      - ../../examples:/var/www/examples
      - ../../schema:/var/www/schema
      - ../xmllint/should-fail:/var/www/scripts/xmllint/should-fail
