version: '3.3'

services:
  php:
    tty: true
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/scripts/php
      - ../../examples:/examples
      - ../../schema:/schema
      - ../xmllint/should-fail:/scripts/xmllint/should-fail
