name: LintForPHP

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: php:8.1-cli
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - run: npm install
    - run: npm run lint
    - run: npm run xmllint
